media_entity.bundle.type.youtube:
  type: mapping
  label: 'YouTube type configuration'
  mapping:
    source_field:
      type: string
      label: 'Field with embed code/URL'

media_entity_youtube.settings:
  type: mapping
  label: 'Media entity YouTube settings'
  mapping:
    local_images:
      type: string
      label: 'Base folder for tuhmbnails'
